# TODO: WRITE ME! (and submit me)

# On "make", the makefile should
#   Compile "src/copysome.c" to the executable (at this level) "copysome"
#   For each "input/[xyz].in", use "copysome" and the -n flag (with NUMLINES) to make
#    the corresponding "output/[xyz].out"

copysome: src/copysome.c
	gcc src/copysome.c -o copysome
